/** Note Actions */
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const SEARCH_NOTES_SUCCESS = "SEARCH_NOTES_SUCCESS";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
