/** Note Category Actions */
export const CREATE_NOTE_CATEGORY_SUCCESS = "CREATE_NOTE_CATEGORY_SUCCESS";
export const DELETE_NOTE_CATEGORY_SUCCESS = "DELETE_NOTE_CATEGORY_SUCCESS";
export const GET_NOTE_CATEGORY_SUCCESS = "GET_NOTE_CATEGORY_SUCCESS";
export const SEARCH_NOTE_CATEGORIES_SUCCESS = "SEARCH_NOTE_CATEGORIES_SUCCESS";
export const UPDATE_NOTE_CATEGORY_SUCCESS = "UPDATE_NOTE_CATEGORY_SUCCESS";

/** Note Actions */
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const SEARCH_NOTES_SUCCESS = "SEARCH_NOTES_SUCCESS";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";

/** Toggle Actions */
export const TOGGLE_NOTE_CATEGORY_MODAL = "TOGGLE_NOTE_CATEGORY_MODAL";
export const TOGGLE_NOTE_MODAL = "TOGGLE_NOTE_MODAL";
